version: 2

conda:
  environment: .rtd-env-py3.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
  jobs:
    pre_build:
      # Generate the thermochem example and reinstall pyrometheus as editable
      - /home/docs/checkouts/readthedocs.org/user_builds/pyrometheus-test/conda/$READTHEDOCS_VERSION/bin/python .ci/generate-example-mech.py test/mechs/sandiego.yaml pyrometheus/thermochem_example.py && /home/docs/checkouts/readthedocs.org/user_builds/pyrometheus-test/conda/$READTHEDOCS_VERSION/bin/python -m pip install --no-cache-dir --editable .
