version: 2

conda:
  environment: .rtd-env-py3.yml

python:
  install:
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
  jobs:
    pre_build:
      # Generate the thermochem example and reinstall pyrometheus as editable
      - python .ci/generate-example-mech.py test/mechs/sandiego.yaml pyrometheus/thermochem_example.py && python -m pip install --editable .
