version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - requirements_doc.txt

sphinx:
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Generate the thermochem example and reinstall pyrometheus as editable
      - python .ci/generate-example-mech.py test/mechs/sandiego.yaml pyrometheus/thermochem_example.py && python -m pip install --no-cache-dir --editable .
