version: 2

conda:
  environment: .rtd-env-py3.yml

python:
  install:
    - method: pip
      path: .

build:
    os: ubuntu-22.04
    tools:
        python: "miniconda3-4.7"
    jobs:
        pre_build:
            - which python && python --version && python .ci/generate-example-mech.py test/mechs/sandiego.yaml pyrometheus/thermochem_example.py && ls pyrometheus
