name: MFC-Integration
on:
    push:
    pull_request:
    schedule:
        - cron: '17 3 * * 0'
 
jobs:
  github:
    name: Github
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: MFlowCode/MFC

      - name: Setup Ubuntu
        run: |
           sudo apt update -y
           sudo apt install -y cmake gcc g++ python3 python3-dev hdf5-tools \
                    libfftw3-dev libhdf5-dev openmpi-bin libopenmpi-dev

      - name: Build
        run:  |
          /bin/bash mfc.sh test --dry-run -j $(nproc) --mpi

      - name: Test
        run:  |
          /bin/bash mfc.sh test -o Chemistry --max-attempts 3 -j $(nproc) --test-all
